name: Deployment Excersise 2
on: push 
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: action/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run test
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: action/checkout@v3
      - name: Install dependencies
        run: npm ci
        run: npm run test
      - name: Test code
      
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: action/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build code  
        run: npm run build
      - name: Deploy code
        run: echo "Deployment done....."

